options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'etl', 'gs://bucket-radic-healthcare/etl/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'sql', 'gs://bucket-radic-healthcare/sql/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'requirements.txt', 'gs://bucket-radic-healthcare/requirements/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'README.md', 'gs://bucket-radic-healthcare/docs/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'cloudbuild.yaml', 'gs://bucket-radic-healthcare/configs/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'dags', 'gs://bucket-radic-healthcare/dags/']
