options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'etl/*', 'gs://bucket-radic-healthcare/etl/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'sql/*', 'gs://bucket-radic-healthcare/sql/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'requirements.txt', 'gs://bucket-radic-healthcare/requirements/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'README.md', 'gs://bucket-radic-healthcare/docs/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'cloudbuild.yaml', 'gs://bucket-radic-healthcare/configs/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'dags/*', 'gs://us-central1-radichealth-pip-2ec2639b-bucket/dags/']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud composer environments update radichealth-pipeline \
        --location=us-central1 \
        --update-pypi-packages-from-file=requirements.txt || echo "No update needed"


- name: 'gcr.io/cloud-builders/curl'
  args:
    - '-X'
    - 'POST'
    - 'https://us-central1-radichealth-pip-2ec2639b-bucket.svc.airflow.googleapis.com/v1/dags/radichealth_etl_daily/dagRuns'
    - '-H'
    - 'Authorization: Bearer $(gcloud auth application-default print-access-token)'
    - '-d'
    - '{"conf": {}}'
